/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace IBridgeStructs {
      
    export type TokenAmountStruct = {tokenId: BigNumberish, amountCurrency: BigNumberish, amountTokens: BigNumberish}

    export type TokenAmountStructOutput = [tokenId: bigint, amountCurrency: bigint, amountTokens: bigint] & {tokenId: bigint, amountCurrency: bigint, amountTokens: bigint }
  

    export type ReceiverWithTokenStruct = {amount: BigNumberish, amountWrapped: BigNumberish, destinationAddress: string, tokenId: BigNumberish}

    export type ReceiverWithTokenStructOutput = [amount: bigint, amountWrapped: bigint, destinationAddress: string, tokenId: bigint] & {amount: bigint, amountWrapped: bigint, destinationAddress: string, tokenId: bigint }
  

    export type BridgingRequestClaimStruct = {observedTransactionHash: BytesLike, receivers: IBridgeStructs.ReceiverWithTokenStruct[], nativeCurrencyAmountSource: BigNumberish, wrappedTokenAmountSource: BigNumberish, nativeCurrencyAmountDestination: BigNumberish, wrappedTokenAmountDestination: BigNumberish, retryCounter: BigNumberish, sourceChainId: BigNumberish, destinationChainId: BigNumberish, bridgeAddrIndex: BigNumberish}

    export type BridgingRequestClaimStructOutput = [observedTransactionHash: string, receivers: IBridgeStructs.ReceiverWithTokenStructOutput[], nativeCurrencyAmountSource: bigint, wrappedTokenAmountSource: bigint, nativeCurrencyAmountDestination: bigint, wrappedTokenAmountDestination: bigint, retryCounter: bigint, sourceChainId: bigint, destinationChainId: bigint, bridgeAddrIndex: bigint] & {observedTransactionHash: string, receivers: IBridgeStructs.ReceiverWithTokenStructOutput[], nativeCurrencyAmountSource: bigint, wrappedTokenAmountSource: bigint, nativeCurrencyAmountDestination: bigint, wrappedTokenAmountDestination: bigint, retryCounter: bigint, sourceChainId: bigint, destinationChainId: bigint, bridgeAddrIndex: bigint }
  

    export type HotWalletIncrementClaimStruct = {chainId: BigNumberish, amount: BigNumberish, amountWrapped: BigNumberish, txHash: BytesLike}

    export type HotWalletIncrementClaimStructOutput = [chainId: bigint, amount: bigint, amountWrapped: bigint, txHash: string] & {chainId: bigint, amount: bigint, amountWrapped: bigint, txHash: string }
  

    export type RefundRequestClaimStruct = {originTransactionHash: BytesLike, refundTransactionHash: BytesLike, originAmount: BigNumberish, originWrappedAmount: BigNumberish, outputIndexes: BytesLike, originSenderAddress: string, retryCounter: BigNumberish, originChainId: BigNumberish, shouldDecrementHotWallet: boolean, destinationChainId: BigNumberish, bridgeAddrIndex: BigNumberish, tokenAmounts: IBridgeStructs.TokenAmountStruct[]}

    export type RefundRequestClaimStructOutput = [originTransactionHash: string, refundTransactionHash: string, originAmount: bigint, originWrappedAmount: bigint, outputIndexes: string, originSenderAddress: string, retryCounter: bigint, originChainId: bigint, shouldDecrementHotWallet: boolean, destinationChainId: bigint, bridgeAddrIndex: bigint, tokenAmounts: IBridgeStructs.TokenAmountStructOutput[]] & {originTransactionHash: string, refundTransactionHash: string, originAmount: bigint, originWrappedAmount: bigint, outputIndexes: string, originSenderAddress: string, retryCounter: bigint, originChainId: bigint, shouldDecrementHotWallet: boolean, destinationChainId: bigint, bridgeAddrIndex: bigint, tokenAmounts: IBridgeStructs.TokenAmountStructOutput[] }
  
    }

  export interface ChainTokensInterface extends Interface {
    getFunction(nameOrSignature: "amountsTo1e18" | "chainTokenQuantity" | "chainWrappedTokenQuantity" | "initialize" | "owner" | "proxiableUUID" | "renounceOwnership" | "setDependencies" | "setInitialTokenQuantities" | "transferOwnership" | "updateChainTokenQuantity" | "updateChainWrappedTokenQuantity" | "updateDefund" | "updateTokensBEFC" | "updateTokensBRC" | "updateTokensHWIC" | "updateTokensRRC" | "upgradeTo" | "upgradeToAndCall" | "validateBRC" | "validateDefund" | "validateRRC" | "version"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AdminChanged" | "AmountsConvertedTo1e18Done" | "BeaconUpgraded" | "ChainDefunded" | "DefundFailedAfterMultipleRetries" | "FundAdminChanged" | "Initialized" | "NotEnoughFunds" | "OwnershipTransferred" | "StakeOperationFailedAfterMultipleRetries" | "TokensRedistributionFailedAfterMultipleRetries" | "UpdatedChainTokenQuantity" | "UpdatedChainWrappedTokenQuantity" | "UpdatedMaxNumberOfTransactions" | "UpdatedTimeoutBlocksNumber" | "Upgraded" | "newChainProposal" | "newChainRegistered"): EventFragment;

    encodeFunctionData(functionFragment: 'amountsTo1e18', values?: undefined): string;
encodeFunctionData(functionFragment: 'chainTokenQuantity', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'chainWrappedTokenQuantity', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'initialize', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'proxiableUUID', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'setDependencies', values: [AddressLike, AddressLike, AddressLike, AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'setInitialTokenQuantities', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updateChainTokenQuantity', values: [BigNumberish, boolean, BigNumberish]): string;
encodeFunctionData(functionFragment: 'updateChainWrappedTokenQuantity', values: [BigNumberish, boolean, BigNumberish]): string;
encodeFunctionData(functionFragment: 'updateDefund', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'updateTokensBEFC', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'updateTokensBRC', values: [IBridgeStructs.BridgingRequestClaimStruct]): string;
encodeFunctionData(functionFragment: 'updateTokensHWIC', values: [IBridgeStructs.HotWalletIncrementClaimStruct]): string;
encodeFunctionData(functionFragment: 'updateTokensRRC', values: [IBridgeStructs.RefundRequestClaimStruct]): string;
encodeFunctionData(functionFragment: 'upgradeTo', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'upgradeToAndCall', values: [AddressLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'validateBRC', values: [IBridgeStructs.BridgingRequestClaimStruct, BigNumberish]): string;
encodeFunctionData(functionFragment: 'validateDefund', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'validateRRC', values: [IBridgeStructs.RefundRequestClaimStruct, BigNumberish]): string;
encodeFunctionData(functionFragment: 'version', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'amountsTo1e18', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'chainTokenQuantity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'chainWrappedTokenQuantity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initialize', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proxiableUUID', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setDependencies', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setInitialTokenQuantities', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateChainTokenQuantity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateChainWrappedTokenQuantity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateDefund', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateTokensBEFC', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateTokensBRC', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateTokensHWIC', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateTokensRRC', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'upgradeTo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'upgradeToAndCall', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'validateBRC', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'validateDefund', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'validateRRC', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'version', data: BytesLike): Result;
  }

  
    export namespace AdminChangedEvent {
      export type InputTuple = [previousAdmin: AddressLike, newAdmin: AddressLike];
      export type OutputTuple = [previousAdmin: string, newAdmin: string];
      export interface OutputObject {previousAdmin: string, newAdmin: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AmountsConvertedTo1e18DoneEvent {
      export type InputTuple = [];
      export type OutputTuple = [];
      export interface OutputObject {};
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BeaconUpgradedEvent {
      export type InputTuple = [beacon: AddressLike];
      export type OutputTuple = [beacon: string];
      export interface OutputObject {beacon: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ChainDefundedEvent {
      export type InputTuple = [_chainId: BigNumberish, _amount: BigNumberish, _amountWrapped: BigNumberish, _tokenAmounts: IBridgeStructs.TokenAmountStruct[], _defundAddress: string];
      export type OutputTuple = [_chainId: bigint, _amount: bigint, _amountWrapped: bigint, _tokenAmounts: IBridgeStructs.TokenAmountStructOutput[], _defundAddress: string];
      export interface OutputObject {_chainId: bigint, _amount: bigint, _amountWrapped: bigint, _tokenAmounts: IBridgeStructs.TokenAmountStructOutput[], _defundAddress: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DefundFailedAfterMultipleRetriesEvent {
      export type InputTuple = [];
      export type OutputTuple = [];
      export interface OutputObject {};
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FundAdminChangedEvent {
      export type InputTuple = [_newFundAdmin: AddressLike];
      export type OutputTuple = [_newFundAdmin: string];
      export interface OutputObject {_newFundAdmin: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace InitializedEvent {
      export type InputTuple = [version: BigNumberish];
      export type OutputTuple = [version: bigint];
      export interface OutputObject {version: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace NotEnoughFundsEvent {
      export type InputTuple = [claimeType: string, index: BigNumberish, availableAmount: BigNumberish];
      export type OutputTuple = [claimeType: string, index: bigint, availableAmount: bigint];
      export interface OutputObject {claimeType: string, index: bigint, availableAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace StakeOperationFailedAfterMultipleRetriesEvent {
      export type InputTuple = [_transactionSubType: BigNumberish];
      export type OutputTuple = [_transactionSubType: bigint];
      export interface OutputObject {_transactionSubType: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TokensRedistributionFailedAfterMultipleRetriesEvent {
      export type InputTuple = [_chainId: BigNumberish];
      export type OutputTuple = [_chainId: bigint];
      export interface OutputObject {_chainId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UpdatedChainTokenQuantityEvent {
      export type InputTuple = [chainId: BigNumberish, isIncrement: boolean, chainTokenQuantity: BigNumberish];
      export type OutputTuple = [chainId: bigint, isIncrement: boolean, chainTokenQuantity: bigint];
      export interface OutputObject {chainId: bigint, isIncrement: boolean, chainTokenQuantity: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UpdatedChainWrappedTokenQuantityEvent {
      export type InputTuple = [chainId: BigNumberish, isIncrement: boolean, chainWrappedTokenQuantity: BigNumberish];
      export type OutputTuple = [chainId: bigint, isIncrement: boolean, chainWrappedTokenQuantity: bigint];
      export interface OutputObject {chainId: bigint, isIncrement: boolean, chainWrappedTokenQuantity: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UpdatedMaxNumberOfTransactionsEvent {
      export type InputTuple = [_maxNumberOfTransactions: BigNumberish];
      export type OutputTuple = [_maxNumberOfTransactions: bigint];
      export interface OutputObject {_maxNumberOfTransactions: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UpdatedTimeoutBlocksNumberEvent {
      export type InputTuple = [_timeoutBlocksNumber: BigNumberish];
      export type OutputTuple = [_timeoutBlocksNumber: bigint];
      export interface OutputObject {_timeoutBlocksNumber: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UpgradedEvent {
      export type InputTuple = [implementation: AddressLike];
      export type OutputTuple = [implementation: string];
      export interface OutputObject {implementation: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace newChainProposalEvent {
      export type InputTuple = [_chainId: BigNumberish, sender: AddressLike];
      export type OutputTuple = [_chainId: bigint, sender: string];
      export interface OutputObject {_chainId: bigint, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace newChainRegisteredEvent {
      export type InputTuple = [_chainId: BigNumberish];
      export type OutputTuple = [_chainId: bigint];
      export interface OutputObject {_chainId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ChainTokens extends BaseContract {
    
    connect(runner?: ContractRunner | null): ChainTokens;
    waitForDeployment(): Promise<this>;

    interface: ChainTokensInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    amountsTo1e18: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    chainTokenQuantity: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    chainWrappedTokenQuantity: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    initialize: TypedContractMethod<
      [_owner: AddressLike, _upgradeAdmin: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    proxiableUUID: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setDependencies: TypedContractMethod<
      [_adminContractAddress: AddressLike, _bridgeAddress: AddressLike, _claimsAddress: AddressLike, _claimsProcessorAddress: AddressLike, _registrationAddress: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setInitialTokenQuantities: TypedContractMethod<
      [_chainId: BigNumberish, _initialTokenSupply: BigNumberish, _initialWrappedTokenSupply: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updateChainTokenQuantity: TypedContractMethod<
      [_chainId: BigNumberish, _isIncrease: boolean, _chainTokenAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    updateChainWrappedTokenQuantity: TypedContractMethod<
      [_chainId: BigNumberish, _isIncrease: boolean, _chainWrappedTokenAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    updateDefund: TypedContractMethod<
      [_chainId: BigNumberish, _amount: BigNumberish, _amountWrapped: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    updateTokensBEFC: TypedContractMethod<
      [chainId: BigNumberish, totalAmount: BigNumberish, totalWrappedAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    updateTokensBRC: TypedContractMethod<
      [_claim: IBridgeStructs.BridgingRequestClaimStruct, ],
      [void],
      'nonpayable'
    >
    

    
    updateTokensHWIC: TypedContractMethod<
      [_claim: IBridgeStructs.HotWalletIncrementClaimStruct, ],
      [void],
      'nonpayable'
    >
    

    
    updateTokensRRC: TypedContractMethod<
      [_claim: IBridgeStructs.RefundRequestClaimStruct, ],
      [void],
      'nonpayable'
    >
    

    
    upgradeTo: TypedContractMethod<
      [newImplementation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    upgradeToAndCall: TypedContractMethod<
      [newImplementation: AddressLike, data: BytesLike, ],
      [void],
      'payable'
    >
    

    
    validateBRC: TypedContractMethod<
      [_claim: IBridgeStructs.BridgingRequestClaimStruct, _index: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    validateDefund: TypedContractMethod<
      [_chainId: BigNumberish, _amount: BigNumberish, _amountWrapped: BigNumberish, ],
      [void],
      'view'
    >
    

    
    validateRRC: TypedContractMethod<
      [_claim: IBridgeStructs.RefundRequestClaimStruct, _index: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    version: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'amountsTo1e18'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'chainTokenQuantity'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'chainWrappedTokenQuantity'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'initialize'): TypedContractMethod<
      [_owner: AddressLike, _upgradeAdmin: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'proxiableUUID'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setDependencies'): TypedContractMethod<
      [_adminContractAddress: AddressLike, _bridgeAddress: AddressLike, _claimsAddress: AddressLike, _claimsProcessorAddress: AddressLike, _registrationAddress: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setInitialTokenQuantities'): TypedContractMethod<
      [_chainId: BigNumberish, _initialTokenSupply: BigNumberish, _initialWrappedTokenSupply: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateChainTokenQuantity'): TypedContractMethod<
      [_chainId: BigNumberish, _isIncrease: boolean, _chainTokenAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateChainWrappedTokenQuantity'): TypedContractMethod<
      [_chainId: BigNumberish, _isIncrease: boolean, _chainWrappedTokenAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateDefund'): TypedContractMethod<
      [_chainId: BigNumberish, _amount: BigNumberish, _amountWrapped: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateTokensBEFC'): TypedContractMethod<
      [chainId: BigNumberish, totalAmount: BigNumberish, totalWrappedAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateTokensBRC'): TypedContractMethod<
      [_claim: IBridgeStructs.BridgingRequestClaimStruct, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateTokensHWIC'): TypedContractMethod<
      [_claim: IBridgeStructs.HotWalletIncrementClaimStruct, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateTokensRRC'): TypedContractMethod<
      [_claim: IBridgeStructs.RefundRequestClaimStruct, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'upgradeTo'): TypedContractMethod<
      [newImplementation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'upgradeToAndCall'): TypedContractMethod<
      [newImplementation: AddressLike, data: BytesLike, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'validateBRC'): TypedContractMethod<
      [_claim: IBridgeStructs.BridgingRequestClaimStruct, _index: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'validateDefund'): TypedContractMethod<
      [_chainId: BigNumberish, _amount: BigNumberish, _amountWrapped: BigNumberish, ],
      [void],
      'view'
    >;
getFunction(nameOrSignature: 'validateRRC'): TypedContractMethod<
      [_claim: IBridgeStructs.RefundRequestClaimStruct, _index: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'version'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'AdminChanged'): TypedContractEvent<AdminChangedEvent.InputTuple, AdminChangedEvent.OutputTuple, AdminChangedEvent.OutputObject>;
getEvent(key: 'AmountsConvertedTo1e18Done'): TypedContractEvent<AmountsConvertedTo1e18DoneEvent.InputTuple, AmountsConvertedTo1e18DoneEvent.OutputTuple, AmountsConvertedTo1e18DoneEvent.OutputObject>;
getEvent(key: 'BeaconUpgraded'): TypedContractEvent<BeaconUpgradedEvent.InputTuple, BeaconUpgradedEvent.OutputTuple, BeaconUpgradedEvent.OutputObject>;
getEvent(key: 'ChainDefunded'): TypedContractEvent<ChainDefundedEvent.InputTuple, ChainDefundedEvent.OutputTuple, ChainDefundedEvent.OutputObject>;
getEvent(key: 'DefundFailedAfterMultipleRetries'): TypedContractEvent<DefundFailedAfterMultipleRetriesEvent.InputTuple, DefundFailedAfterMultipleRetriesEvent.OutputTuple, DefundFailedAfterMultipleRetriesEvent.OutputObject>;
getEvent(key: 'FundAdminChanged'): TypedContractEvent<FundAdminChangedEvent.InputTuple, FundAdminChangedEvent.OutputTuple, FundAdminChangedEvent.OutputObject>;
getEvent(key: 'Initialized'): TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
getEvent(key: 'NotEnoughFunds'): TypedContractEvent<NotEnoughFundsEvent.InputTuple, NotEnoughFundsEvent.OutputTuple, NotEnoughFundsEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'StakeOperationFailedAfterMultipleRetries'): TypedContractEvent<StakeOperationFailedAfterMultipleRetriesEvent.InputTuple, StakeOperationFailedAfterMultipleRetriesEvent.OutputTuple, StakeOperationFailedAfterMultipleRetriesEvent.OutputObject>;
getEvent(key: 'TokensRedistributionFailedAfterMultipleRetries'): TypedContractEvent<TokensRedistributionFailedAfterMultipleRetriesEvent.InputTuple, TokensRedistributionFailedAfterMultipleRetriesEvent.OutputTuple, TokensRedistributionFailedAfterMultipleRetriesEvent.OutputObject>;
getEvent(key: 'UpdatedChainTokenQuantity'): TypedContractEvent<UpdatedChainTokenQuantityEvent.InputTuple, UpdatedChainTokenQuantityEvent.OutputTuple, UpdatedChainTokenQuantityEvent.OutputObject>;
getEvent(key: 'UpdatedChainWrappedTokenQuantity'): TypedContractEvent<UpdatedChainWrappedTokenQuantityEvent.InputTuple, UpdatedChainWrappedTokenQuantityEvent.OutputTuple, UpdatedChainWrappedTokenQuantityEvent.OutputObject>;
getEvent(key: 'UpdatedMaxNumberOfTransactions'): TypedContractEvent<UpdatedMaxNumberOfTransactionsEvent.InputTuple, UpdatedMaxNumberOfTransactionsEvent.OutputTuple, UpdatedMaxNumberOfTransactionsEvent.OutputObject>;
getEvent(key: 'UpdatedTimeoutBlocksNumber'): TypedContractEvent<UpdatedTimeoutBlocksNumberEvent.InputTuple, UpdatedTimeoutBlocksNumberEvent.OutputTuple, UpdatedTimeoutBlocksNumberEvent.OutputObject>;
getEvent(key: 'Upgraded'): TypedContractEvent<UpgradedEvent.InputTuple, UpgradedEvent.OutputTuple, UpgradedEvent.OutputObject>;
getEvent(key: 'newChainProposal'): TypedContractEvent<newChainProposalEvent.InputTuple, newChainProposalEvent.OutputTuple, newChainProposalEvent.OutputObject>;
getEvent(key: 'newChainRegistered'): TypedContractEvent<newChainRegisteredEvent.InputTuple, newChainRegisteredEvent.OutputTuple, newChainRegisteredEvent.OutputObject>;

    filters: {
      
      'AdminChanged(address,address)': TypedContractEvent<AdminChangedEvent.InputTuple, AdminChangedEvent.OutputTuple, AdminChangedEvent.OutputObject>;
      AdminChanged: TypedContractEvent<AdminChangedEvent.InputTuple, AdminChangedEvent.OutputTuple, AdminChangedEvent.OutputObject>;
    

      'AmountsConvertedTo1e18Done()': TypedContractEvent<AmountsConvertedTo1e18DoneEvent.InputTuple, AmountsConvertedTo1e18DoneEvent.OutputTuple, AmountsConvertedTo1e18DoneEvent.OutputObject>;
      AmountsConvertedTo1e18Done: TypedContractEvent<AmountsConvertedTo1e18DoneEvent.InputTuple, AmountsConvertedTo1e18DoneEvent.OutputTuple, AmountsConvertedTo1e18DoneEvent.OutputObject>;
    

      'BeaconUpgraded(address)': TypedContractEvent<BeaconUpgradedEvent.InputTuple, BeaconUpgradedEvent.OutputTuple, BeaconUpgradedEvent.OutputObject>;
      BeaconUpgraded: TypedContractEvent<BeaconUpgradedEvent.InputTuple, BeaconUpgradedEvent.OutputTuple, BeaconUpgradedEvent.OutputObject>;
    

      'ChainDefunded(uint8,uint256,uint256,tuple[],string)': TypedContractEvent<ChainDefundedEvent.InputTuple, ChainDefundedEvent.OutputTuple, ChainDefundedEvent.OutputObject>;
      ChainDefunded: TypedContractEvent<ChainDefundedEvent.InputTuple, ChainDefundedEvent.OutputTuple, ChainDefundedEvent.OutputObject>;
    

      'DefundFailedAfterMultipleRetries()': TypedContractEvent<DefundFailedAfterMultipleRetriesEvent.InputTuple, DefundFailedAfterMultipleRetriesEvent.OutputTuple, DefundFailedAfterMultipleRetriesEvent.OutputObject>;
      DefundFailedAfterMultipleRetries: TypedContractEvent<DefundFailedAfterMultipleRetriesEvent.InputTuple, DefundFailedAfterMultipleRetriesEvent.OutputTuple, DefundFailedAfterMultipleRetriesEvent.OutputObject>;
    

      'FundAdminChanged(address)': TypedContractEvent<FundAdminChangedEvent.InputTuple, FundAdminChangedEvent.OutputTuple, FundAdminChangedEvent.OutputObject>;
      FundAdminChanged: TypedContractEvent<FundAdminChangedEvent.InputTuple, FundAdminChangedEvent.OutputTuple, FundAdminChangedEvent.OutputObject>;
    

      'Initialized(uint8)': TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
      Initialized: TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
    

      'NotEnoughFunds(string,uint256,uint256)': TypedContractEvent<NotEnoughFundsEvent.InputTuple, NotEnoughFundsEvent.OutputTuple, NotEnoughFundsEvent.OutputObject>;
      NotEnoughFunds: TypedContractEvent<NotEnoughFundsEvent.InputTuple, NotEnoughFundsEvent.OutputTuple, NotEnoughFundsEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'StakeOperationFailedAfterMultipleRetries(uint8)': TypedContractEvent<StakeOperationFailedAfterMultipleRetriesEvent.InputTuple, StakeOperationFailedAfterMultipleRetriesEvent.OutputTuple, StakeOperationFailedAfterMultipleRetriesEvent.OutputObject>;
      StakeOperationFailedAfterMultipleRetries: TypedContractEvent<StakeOperationFailedAfterMultipleRetriesEvent.InputTuple, StakeOperationFailedAfterMultipleRetriesEvent.OutputTuple, StakeOperationFailedAfterMultipleRetriesEvent.OutputObject>;
    

      'TokensRedistributionFailedAfterMultipleRetries(uint8)': TypedContractEvent<TokensRedistributionFailedAfterMultipleRetriesEvent.InputTuple, TokensRedistributionFailedAfterMultipleRetriesEvent.OutputTuple, TokensRedistributionFailedAfterMultipleRetriesEvent.OutputObject>;
      TokensRedistributionFailedAfterMultipleRetries: TypedContractEvent<TokensRedistributionFailedAfterMultipleRetriesEvent.InputTuple, TokensRedistributionFailedAfterMultipleRetriesEvent.OutputTuple, TokensRedistributionFailedAfterMultipleRetriesEvent.OutputObject>;
    

      'UpdatedChainTokenQuantity(uint256,bool,uint256)': TypedContractEvent<UpdatedChainTokenQuantityEvent.InputTuple, UpdatedChainTokenQuantityEvent.OutputTuple, UpdatedChainTokenQuantityEvent.OutputObject>;
      UpdatedChainTokenQuantity: TypedContractEvent<UpdatedChainTokenQuantityEvent.InputTuple, UpdatedChainTokenQuantityEvent.OutputTuple, UpdatedChainTokenQuantityEvent.OutputObject>;
    

      'UpdatedChainWrappedTokenQuantity(uint256,bool,uint256)': TypedContractEvent<UpdatedChainWrappedTokenQuantityEvent.InputTuple, UpdatedChainWrappedTokenQuantityEvent.OutputTuple, UpdatedChainWrappedTokenQuantityEvent.OutputObject>;
      UpdatedChainWrappedTokenQuantity: TypedContractEvent<UpdatedChainWrappedTokenQuantityEvent.InputTuple, UpdatedChainWrappedTokenQuantityEvent.OutputTuple, UpdatedChainWrappedTokenQuantityEvent.OutputObject>;
    

      'UpdatedMaxNumberOfTransactions(uint256)': TypedContractEvent<UpdatedMaxNumberOfTransactionsEvent.InputTuple, UpdatedMaxNumberOfTransactionsEvent.OutputTuple, UpdatedMaxNumberOfTransactionsEvent.OutputObject>;
      UpdatedMaxNumberOfTransactions: TypedContractEvent<UpdatedMaxNumberOfTransactionsEvent.InputTuple, UpdatedMaxNumberOfTransactionsEvent.OutputTuple, UpdatedMaxNumberOfTransactionsEvent.OutputObject>;
    

      'UpdatedTimeoutBlocksNumber(uint256)': TypedContractEvent<UpdatedTimeoutBlocksNumberEvent.InputTuple, UpdatedTimeoutBlocksNumberEvent.OutputTuple, UpdatedTimeoutBlocksNumberEvent.OutputObject>;
      UpdatedTimeoutBlocksNumber: TypedContractEvent<UpdatedTimeoutBlocksNumberEvent.InputTuple, UpdatedTimeoutBlocksNumberEvent.OutputTuple, UpdatedTimeoutBlocksNumberEvent.OutputObject>;
    

      'Upgraded(address)': TypedContractEvent<UpgradedEvent.InputTuple, UpgradedEvent.OutputTuple, UpgradedEvent.OutputObject>;
      Upgraded: TypedContractEvent<UpgradedEvent.InputTuple, UpgradedEvent.OutputTuple, UpgradedEvent.OutputObject>;
    

      'newChainProposal(uint8,address)': TypedContractEvent<newChainProposalEvent.InputTuple, newChainProposalEvent.OutputTuple, newChainProposalEvent.OutputObject>;
      newChainProposal: TypedContractEvent<newChainProposalEvent.InputTuple, newChainProposalEvent.OutputTuple, newChainProposalEvent.OutputObject>;
    

      'newChainRegistered(uint8)': TypedContractEvent<newChainRegisteredEvent.InputTuple, newChainRegisteredEvent.OutputTuple, newChainRegisteredEvent.OutputObject>;
      newChainRegistered: TypedContractEvent<newChainRegisteredEvent.InputTuple, newChainRegisteredEvent.OutputTuple, newChainRegisteredEvent.OutputObject>;
    
    };
  }