/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'Admin', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Admin__factory>
getContractFactory(name: 'Bridge', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Bridge__factory>
getContractFactory(name: 'Claims', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Claims__factory>
getContractFactory(name: 'ClaimsHelper', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ClaimsHelper__factory>
getContractFactory(name: 'SignedBatches', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SignedBatches__factory>
getContractFactory(name: 'Slots', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Slots__factory>
getContractFactory(name: 'UUPSProxy', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.UUPSProxy__factory>
getContractFactory(name: 'Validators', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Validators__factory>
getContractFactory(name: 'IBridge', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IBridge__factory>
getContractFactory(name: 'IBridgeStructs', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IBridgeStructs__factory>
getContractFactory(name: 'MockPrecompileFalse', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockPrecompileFalse__factory>
getContractFactory(name: 'MockPrecompileTrue', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockPrecompileTrue__factory>

  getContractAt(name: 'Admin', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Admin>
getContractAt(name: 'Bridge', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Bridge>
getContractAt(name: 'Claims', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Claims>
getContractAt(name: 'ClaimsHelper', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ClaimsHelper>
getContractAt(name: 'SignedBatches', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SignedBatches>
getContractAt(name: 'Slots', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Slots>
getContractAt(name: 'UUPSProxy', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.UUPSProxy>
getContractAt(name: 'Validators', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Validators>
getContractAt(name: 'IBridge', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IBridge>
getContractAt(name: 'IBridgeStructs', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IBridgeStructs>
getContractAt(name: 'MockPrecompileFalse', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockPrecompileFalse>
getContractAt(name: 'MockPrecompileTrue', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockPrecompileTrue>

  deployContract(name: 'Admin', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Admin>
deployContract(name: 'Bridge', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Bridge>
deployContract(name: 'Claims', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Claims>
deployContract(name: 'ClaimsHelper', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ClaimsHelper>
deployContract(name: 'SignedBatches', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SignedBatches>
deployContract(name: 'Slots', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Slots>
deployContract(name: 'UUPSProxy', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.UUPSProxy>
deployContract(name: 'Validators', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Validators>
deployContract(name: 'IBridge', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IBridge>
deployContract(name: 'IBridgeStructs', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IBridgeStructs>
deployContract(name: 'MockPrecompileFalse', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockPrecompileFalse>
deployContract(name: 'MockPrecompileTrue', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockPrecompileTrue>

  deployContract(name: 'Admin', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Admin>
deployContract(name: 'Bridge', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Bridge>
deployContract(name: 'Claims', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Claims>
deployContract(name: 'ClaimsHelper', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ClaimsHelper>
deployContract(name: 'SignedBatches', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SignedBatches>
deployContract(name: 'Slots', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Slots>
deployContract(name: 'UUPSProxy', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.UUPSProxy>
deployContract(name: 'Validators', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Validators>
deployContract(name: 'IBridge', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IBridge>
deployContract(name: 'IBridgeStructs', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IBridgeStructs>
deployContract(name: 'MockPrecompileFalse', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockPrecompileFalse>
deployContract(name: 'MockPrecompileTrue', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockPrecompileTrue>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  