/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace IBridgeStructs {
      
    export type TokenAmountStruct = {tokenId: BigNumberish, amountCurrency: BigNumberish, amountTokens: BigNumberish}

    export type TokenAmountStructOutput = [tokenId: bigint, amountCurrency: bigint, amountTokens: bigint] & {tokenId: bigint, amountCurrency: bigint, amountTokens: bigint }
  

    export type ChainStruct = {id: BigNumberish, chainType: BigNumberish, addressMultisig: string, addressFeePayer: string}

    export type ChainStructOutput = [id: bigint, chainType: bigint, addressMultisig: string, addressFeePayer: string] & {id: bigint, chainType: bigint, addressMultisig: string, addressFeePayer: string }
  

    export type ValidatorChainDataStruct = {key: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]}

    export type ValidatorChainDataStructOutput = [key: [bigint, bigint, bigint, bigint]] & {key: [bigint, bigint, bigint, bigint] }
  

    export type ValidatorAddressChainDataStruct = {addr: AddressLike, data: IBridgeStructs.ValidatorChainDataStruct, keySignature: BytesLike, keyFeeSignature: BytesLike}

    export type ValidatorAddressChainDataStructOutput = [addr: string, data: IBridgeStructs.ValidatorChainDataStructOutput, keySignature: string, keyFeeSignature: string] & {addr: string, data: IBridgeStructs.ValidatorChainDataStructOutput, keySignature: string, keyFeeSignature: string }
  
    }

  export interface RegistrationInterface extends Interface {
    getFunction(nameOrSignature: "addChain" | "getAllRegisteredChains" | "initialize" | "owner" | "proxiableUUID" | "registerChain" | "registerChainGovernance" | "renounceOwnership" | "setChainAdditionalData" | "setDependencies" | "transferOwnership" | "upgradeTo" | "upgradeToAndCall" | "version"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AdminChanged" | "BeaconUpgraded" | "ChainDefunded" | "DefundFailedAfterMultipleRetries" | "FundAdminChanged" | "Initialized" | "NotEnoughFunds" | "OwnershipTransferred" | "StakeOperationFailedAfterMultipleRetries" | "TokensRedistributionFailedAfterMultipleRetries" | "UpdatedChainTokenQuantity" | "UpdatedChainWrappedTokenQuantity" | "UpdatedMaxNumberOfTransactions" | "UpdatedTimeoutBlocksNumber" | "Upgraded" | "newChainProposal" | "newChainRegistered"): EventFragment;

    encodeFunctionData(functionFragment: 'addChain', values: [IBridgeStructs.ChainStruct]): string;
encodeFunctionData(functionFragment: 'getAllRegisteredChains', values?: undefined): string;
encodeFunctionData(functionFragment: 'initialize', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'proxiableUUID', values?: undefined): string;
encodeFunctionData(functionFragment: 'registerChain', values: [IBridgeStructs.ChainStruct, BigNumberish, BigNumberish, IBridgeStructs.ValidatorAddressChainDataStruct[]]): string;
encodeFunctionData(functionFragment: 'registerChainGovernance', values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish, IBridgeStructs.ValidatorChainDataStruct, BytesLike, BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'setChainAdditionalData', values: [BigNumberish, string, string]): string;
encodeFunctionData(functionFragment: 'setDependencies', values: [AddressLike, AddressLike, AddressLike, AddressLike, AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'upgradeTo', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'upgradeToAndCall', values: [AddressLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'version', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'addChain', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAllRegisteredChains', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initialize', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proxiableUUID', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerChain', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerChainGovernance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setChainAdditionalData', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setDependencies', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'upgradeTo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'upgradeToAndCall', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'version', data: BytesLike): Result;
  }

  
    export namespace AdminChangedEvent {
      export type InputTuple = [previousAdmin: AddressLike, newAdmin: AddressLike];
      export type OutputTuple = [previousAdmin: string, newAdmin: string];
      export interface OutputObject {previousAdmin: string, newAdmin: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BeaconUpgradedEvent {
      export type InputTuple = [beacon: AddressLike];
      export type OutputTuple = [beacon: string];
      export interface OutputObject {beacon: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ChainDefundedEvent {
      export type InputTuple = [_chainId: BigNumberish, _amount: BigNumberish, _amountWrapped: BigNumberish, _tokenAmounts: IBridgeStructs.TokenAmountStruct[], _defundAddress: string];
      export type OutputTuple = [_chainId: bigint, _amount: bigint, _amountWrapped: bigint, _tokenAmounts: IBridgeStructs.TokenAmountStructOutput[], _defundAddress: string];
      export interface OutputObject {_chainId: bigint, _amount: bigint, _amountWrapped: bigint, _tokenAmounts: IBridgeStructs.TokenAmountStructOutput[], _defundAddress: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DefundFailedAfterMultipleRetriesEvent {
      export type InputTuple = [];
      export type OutputTuple = [];
      export interface OutputObject {};
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FundAdminChangedEvent {
      export type InputTuple = [_newFundAdmin: AddressLike];
      export type OutputTuple = [_newFundAdmin: string];
      export interface OutputObject {_newFundAdmin: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace InitializedEvent {
      export type InputTuple = [version: BigNumberish];
      export type OutputTuple = [version: bigint];
      export interface OutputObject {version: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace NotEnoughFundsEvent {
      export type InputTuple = [claimeType: string, index: BigNumberish, availableAmount: BigNumberish];
      export type OutputTuple = [claimeType: string, index: bigint, availableAmount: bigint];
      export interface OutputObject {claimeType: string, index: bigint, availableAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace StakeOperationFailedAfterMultipleRetriesEvent {
      export type InputTuple = [_transactionSubType: BigNumberish];
      export type OutputTuple = [_transactionSubType: bigint];
      export interface OutputObject {_transactionSubType: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TokensRedistributionFailedAfterMultipleRetriesEvent {
      export type InputTuple = [_chainId: BigNumberish];
      export type OutputTuple = [_chainId: bigint];
      export interface OutputObject {_chainId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UpdatedChainTokenQuantityEvent {
      export type InputTuple = [chainId: BigNumberish, isIncrement: boolean, chainTokenQuantity: BigNumberish];
      export type OutputTuple = [chainId: bigint, isIncrement: boolean, chainTokenQuantity: bigint];
      export interface OutputObject {chainId: bigint, isIncrement: boolean, chainTokenQuantity: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UpdatedChainWrappedTokenQuantityEvent {
      export type InputTuple = [chainId: BigNumberish, isIncrement: boolean, chainWrappedTokenQuantity: BigNumberish];
      export type OutputTuple = [chainId: bigint, isIncrement: boolean, chainWrappedTokenQuantity: bigint];
      export interface OutputObject {chainId: bigint, isIncrement: boolean, chainWrappedTokenQuantity: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UpdatedMaxNumberOfTransactionsEvent {
      export type InputTuple = [_maxNumberOfTransactions: BigNumberish];
      export type OutputTuple = [_maxNumberOfTransactions: bigint];
      export interface OutputObject {_maxNumberOfTransactions: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UpdatedTimeoutBlocksNumberEvent {
      export type InputTuple = [_timeoutBlocksNumber: BigNumberish];
      export type OutputTuple = [_timeoutBlocksNumber: bigint];
      export interface OutputObject {_timeoutBlocksNumber: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UpgradedEvent {
      export type InputTuple = [implementation: AddressLike];
      export type OutputTuple = [implementation: string];
      export interface OutputObject {implementation: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace newChainProposalEvent {
      export type InputTuple = [_chainId: BigNumberish, sender: AddressLike];
      export type OutputTuple = [_chainId: bigint, sender: string];
      export interface OutputObject {_chainId: bigint, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace newChainRegisteredEvent {
      export type InputTuple = [_chainId: BigNumberish];
      export type OutputTuple = [_chainId: bigint];
      export interface OutputObject {_chainId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Registration extends BaseContract {
    
    connect(runner?: ContractRunner | null): Registration;
    waitForDeployment(): Promise<this>;

    interface: RegistrationInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addChain: TypedContractMethod<
      [_chain: IBridgeStructs.ChainStruct, ],
      [void],
      'nonpayable'
    >
    

    
    getAllRegisteredChains: TypedContractMethod<
      [],
      [IBridgeStructs.ChainStructOutput[]],
      'view'
    >
    

    
    initialize: TypedContractMethod<
      [_owner: AddressLike, _upgradeAdmin: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    proxiableUUID: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    registerChain: TypedContractMethod<
      [_chain: IBridgeStructs.ChainStruct, _tokenQuantity: BigNumberish, _wrappedTokenQuantity: BigNumberish, _validatorData: IBridgeStructs.ValidatorAddressChainDataStruct[], ],
      [void],
      'nonpayable'
    >
    

    
    registerChainGovernance: TypedContractMethod<
      [_chainId: BigNumberish, _chainType: BigNumberish, _tokenQuantity: BigNumberish, _wrappedTokenQuantity: BigNumberish, _validatorChainData: IBridgeStructs.ValidatorChainDataStruct, _keySignature: BytesLike, _keyFeeSignature: BytesLike, _caller: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setChainAdditionalData: TypedContractMethod<
      [_chainId: BigNumberish, addressMultisig: string, addressFeePayer: string, ],
      [void],
      'nonpayable'
    >
    

    
    setDependencies: TypedContractMethod<
      [_bridgeAddress: AddressLike, _bridgingAddressesAddress: AddressLike, _chainTokensAddress: AddressLike, _claimsAddress: AddressLike, _claimsHelperAddress: AddressLike, _validatorsAddress: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    upgradeTo: TypedContractMethod<
      [newImplementation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    upgradeToAndCall: TypedContractMethod<
      [newImplementation: AddressLike, data: BytesLike, ],
      [void],
      'payable'
    >
    

    
    version: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addChain'): TypedContractMethod<
      [_chain: IBridgeStructs.ChainStruct, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getAllRegisteredChains'): TypedContractMethod<
      [],
      [IBridgeStructs.ChainStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'initialize'): TypedContractMethod<
      [_owner: AddressLike, _upgradeAdmin: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'proxiableUUID'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'registerChain'): TypedContractMethod<
      [_chain: IBridgeStructs.ChainStruct, _tokenQuantity: BigNumberish, _wrappedTokenQuantity: BigNumberish, _validatorData: IBridgeStructs.ValidatorAddressChainDataStruct[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'registerChainGovernance'): TypedContractMethod<
      [_chainId: BigNumberish, _chainType: BigNumberish, _tokenQuantity: BigNumberish, _wrappedTokenQuantity: BigNumberish, _validatorChainData: IBridgeStructs.ValidatorChainDataStruct, _keySignature: BytesLike, _keyFeeSignature: BytesLike, _caller: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setChainAdditionalData'): TypedContractMethod<
      [_chainId: BigNumberish, addressMultisig: string, addressFeePayer: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setDependencies'): TypedContractMethod<
      [_bridgeAddress: AddressLike, _bridgingAddressesAddress: AddressLike, _chainTokensAddress: AddressLike, _claimsAddress: AddressLike, _claimsHelperAddress: AddressLike, _validatorsAddress: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'upgradeTo'): TypedContractMethod<
      [newImplementation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'upgradeToAndCall'): TypedContractMethod<
      [newImplementation: AddressLike, data: BytesLike, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'version'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'AdminChanged'): TypedContractEvent<AdminChangedEvent.InputTuple, AdminChangedEvent.OutputTuple, AdminChangedEvent.OutputObject>;
getEvent(key: 'BeaconUpgraded'): TypedContractEvent<BeaconUpgradedEvent.InputTuple, BeaconUpgradedEvent.OutputTuple, BeaconUpgradedEvent.OutputObject>;
getEvent(key: 'ChainDefunded'): TypedContractEvent<ChainDefundedEvent.InputTuple, ChainDefundedEvent.OutputTuple, ChainDefundedEvent.OutputObject>;
getEvent(key: 'DefundFailedAfterMultipleRetries'): TypedContractEvent<DefundFailedAfterMultipleRetriesEvent.InputTuple, DefundFailedAfterMultipleRetriesEvent.OutputTuple, DefundFailedAfterMultipleRetriesEvent.OutputObject>;
getEvent(key: 'FundAdminChanged'): TypedContractEvent<FundAdminChangedEvent.InputTuple, FundAdminChangedEvent.OutputTuple, FundAdminChangedEvent.OutputObject>;
getEvent(key: 'Initialized'): TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
getEvent(key: 'NotEnoughFunds'): TypedContractEvent<NotEnoughFundsEvent.InputTuple, NotEnoughFundsEvent.OutputTuple, NotEnoughFundsEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'StakeOperationFailedAfterMultipleRetries'): TypedContractEvent<StakeOperationFailedAfterMultipleRetriesEvent.InputTuple, StakeOperationFailedAfterMultipleRetriesEvent.OutputTuple, StakeOperationFailedAfterMultipleRetriesEvent.OutputObject>;
getEvent(key: 'TokensRedistributionFailedAfterMultipleRetries'): TypedContractEvent<TokensRedistributionFailedAfterMultipleRetriesEvent.InputTuple, TokensRedistributionFailedAfterMultipleRetriesEvent.OutputTuple, TokensRedistributionFailedAfterMultipleRetriesEvent.OutputObject>;
getEvent(key: 'UpdatedChainTokenQuantity'): TypedContractEvent<UpdatedChainTokenQuantityEvent.InputTuple, UpdatedChainTokenQuantityEvent.OutputTuple, UpdatedChainTokenQuantityEvent.OutputObject>;
getEvent(key: 'UpdatedChainWrappedTokenQuantity'): TypedContractEvent<UpdatedChainWrappedTokenQuantityEvent.InputTuple, UpdatedChainWrappedTokenQuantityEvent.OutputTuple, UpdatedChainWrappedTokenQuantityEvent.OutputObject>;
getEvent(key: 'UpdatedMaxNumberOfTransactions'): TypedContractEvent<UpdatedMaxNumberOfTransactionsEvent.InputTuple, UpdatedMaxNumberOfTransactionsEvent.OutputTuple, UpdatedMaxNumberOfTransactionsEvent.OutputObject>;
getEvent(key: 'UpdatedTimeoutBlocksNumber'): TypedContractEvent<UpdatedTimeoutBlocksNumberEvent.InputTuple, UpdatedTimeoutBlocksNumberEvent.OutputTuple, UpdatedTimeoutBlocksNumberEvent.OutputObject>;
getEvent(key: 'Upgraded'): TypedContractEvent<UpgradedEvent.InputTuple, UpgradedEvent.OutputTuple, UpgradedEvent.OutputObject>;
getEvent(key: 'newChainProposal'): TypedContractEvent<newChainProposalEvent.InputTuple, newChainProposalEvent.OutputTuple, newChainProposalEvent.OutputObject>;
getEvent(key: 'newChainRegistered'): TypedContractEvent<newChainRegisteredEvent.InputTuple, newChainRegisteredEvent.OutputTuple, newChainRegisteredEvent.OutputObject>;

    filters: {
      
      'AdminChanged(address,address)': TypedContractEvent<AdminChangedEvent.InputTuple, AdminChangedEvent.OutputTuple, AdminChangedEvent.OutputObject>;
      AdminChanged: TypedContractEvent<AdminChangedEvent.InputTuple, AdminChangedEvent.OutputTuple, AdminChangedEvent.OutputObject>;
    

      'BeaconUpgraded(address)': TypedContractEvent<BeaconUpgradedEvent.InputTuple, BeaconUpgradedEvent.OutputTuple, BeaconUpgradedEvent.OutputObject>;
      BeaconUpgraded: TypedContractEvent<BeaconUpgradedEvent.InputTuple, BeaconUpgradedEvent.OutputTuple, BeaconUpgradedEvent.OutputObject>;
    

      'ChainDefunded(uint8,uint256,uint256,tuple[],string)': TypedContractEvent<ChainDefundedEvent.InputTuple, ChainDefundedEvent.OutputTuple, ChainDefundedEvent.OutputObject>;
      ChainDefunded: TypedContractEvent<ChainDefundedEvent.InputTuple, ChainDefundedEvent.OutputTuple, ChainDefundedEvent.OutputObject>;
    

      'DefundFailedAfterMultipleRetries()': TypedContractEvent<DefundFailedAfterMultipleRetriesEvent.InputTuple, DefundFailedAfterMultipleRetriesEvent.OutputTuple, DefundFailedAfterMultipleRetriesEvent.OutputObject>;
      DefundFailedAfterMultipleRetries: TypedContractEvent<DefundFailedAfterMultipleRetriesEvent.InputTuple, DefundFailedAfterMultipleRetriesEvent.OutputTuple, DefundFailedAfterMultipleRetriesEvent.OutputObject>;
    

      'FundAdminChanged(address)': TypedContractEvent<FundAdminChangedEvent.InputTuple, FundAdminChangedEvent.OutputTuple, FundAdminChangedEvent.OutputObject>;
      FundAdminChanged: TypedContractEvent<FundAdminChangedEvent.InputTuple, FundAdminChangedEvent.OutputTuple, FundAdminChangedEvent.OutputObject>;
    

      'Initialized(uint8)': TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
      Initialized: TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
    

      'NotEnoughFunds(string,uint256,uint256)': TypedContractEvent<NotEnoughFundsEvent.InputTuple, NotEnoughFundsEvent.OutputTuple, NotEnoughFundsEvent.OutputObject>;
      NotEnoughFunds: TypedContractEvent<NotEnoughFundsEvent.InputTuple, NotEnoughFundsEvent.OutputTuple, NotEnoughFundsEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'StakeOperationFailedAfterMultipleRetries(uint8)': TypedContractEvent<StakeOperationFailedAfterMultipleRetriesEvent.InputTuple, StakeOperationFailedAfterMultipleRetriesEvent.OutputTuple, StakeOperationFailedAfterMultipleRetriesEvent.OutputObject>;
      StakeOperationFailedAfterMultipleRetries: TypedContractEvent<StakeOperationFailedAfterMultipleRetriesEvent.InputTuple, StakeOperationFailedAfterMultipleRetriesEvent.OutputTuple, StakeOperationFailedAfterMultipleRetriesEvent.OutputObject>;
    

      'TokensRedistributionFailedAfterMultipleRetries(uint8)': TypedContractEvent<TokensRedistributionFailedAfterMultipleRetriesEvent.InputTuple, TokensRedistributionFailedAfterMultipleRetriesEvent.OutputTuple, TokensRedistributionFailedAfterMultipleRetriesEvent.OutputObject>;
      TokensRedistributionFailedAfterMultipleRetries: TypedContractEvent<TokensRedistributionFailedAfterMultipleRetriesEvent.InputTuple, TokensRedistributionFailedAfterMultipleRetriesEvent.OutputTuple, TokensRedistributionFailedAfterMultipleRetriesEvent.OutputObject>;
    

      'UpdatedChainTokenQuantity(uint256,bool,uint256)': TypedContractEvent<UpdatedChainTokenQuantityEvent.InputTuple, UpdatedChainTokenQuantityEvent.OutputTuple, UpdatedChainTokenQuantityEvent.OutputObject>;
      UpdatedChainTokenQuantity: TypedContractEvent<UpdatedChainTokenQuantityEvent.InputTuple, UpdatedChainTokenQuantityEvent.OutputTuple, UpdatedChainTokenQuantityEvent.OutputObject>;
    

      'UpdatedChainWrappedTokenQuantity(uint256,bool,uint256)': TypedContractEvent<UpdatedChainWrappedTokenQuantityEvent.InputTuple, UpdatedChainWrappedTokenQuantityEvent.OutputTuple, UpdatedChainWrappedTokenQuantityEvent.OutputObject>;
      UpdatedChainWrappedTokenQuantity: TypedContractEvent<UpdatedChainWrappedTokenQuantityEvent.InputTuple, UpdatedChainWrappedTokenQuantityEvent.OutputTuple, UpdatedChainWrappedTokenQuantityEvent.OutputObject>;
    

      'UpdatedMaxNumberOfTransactions(uint256)': TypedContractEvent<UpdatedMaxNumberOfTransactionsEvent.InputTuple, UpdatedMaxNumberOfTransactionsEvent.OutputTuple, UpdatedMaxNumberOfTransactionsEvent.OutputObject>;
      UpdatedMaxNumberOfTransactions: TypedContractEvent<UpdatedMaxNumberOfTransactionsEvent.InputTuple, UpdatedMaxNumberOfTransactionsEvent.OutputTuple, UpdatedMaxNumberOfTransactionsEvent.OutputObject>;
    

      'UpdatedTimeoutBlocksNumber(uint256)': TypedContractEvent<UpdatedTimeoutBlocksNumberEvent.InputTuple, UpdatedTimeoutBlocksNumberEvent.OutputTuple, UpdatedTimeoutBlocksNumberEvent.OutputObject>;
      UpdatedTimeoutBlocksNumber: TypedContractEvent<UpdatedTimeoutBlocksNumberEvent.InputTuple, UpdatedTimeoutBlocksNumberEvent.OutputTuple, UpdatedTimeoutBlocksNumberEvent.OutputObject>;
    

      'Upgraded(address)': TypedContractEvent<UpgradedEvent.InputTuple, UpgradedEvent.OutputTuple, UpgradedEvent.OutputObject>;
      Upgraded: TypedContractEvent<UpgradedEvent.InputTuple, UpgradedEvent.OutputTuple, UpgradedEvent.OutputObject>;
    

      'newChainProposal(uint8,address)': TypedContractEvent<newChainProposalEvent.InputTuple, newChainProposalEvent.OutputTuple, newChainProposalEvent.OutputObject>;
      newChainProposal: TypedContractEvent<newChainProposalEvent.InputTuple, newChainProposalEvent.OutputTuple, newChainProposalEvent.OutputObject>;
    

      'newChainRegistered(uint8)': TypedContractEvent<newChainRegisteredEvent.InputTuple, newChainRegisteredEvent.OutputTuple, newChainRegisteredEvent.OutputObject>;
      newChainRegistered: TypedContractEvent<newChainRegisteredEvent.InputTuple, newChainRegisteredEvent.OutputTuple, newChainRegisteredEvent.OutputObject>;
    
    };
  }